"""Ansatz generation and representation APIs for Verfeinert."""

from .campaign_spec import (
    load_and_validate_campaign_spec,
    load_campaign_spec,
    validate_campaign_spec,
    write_campaign_spec,
)
from .candidates import CandidateRecord
from .compilation import (
    CANDIDATE_HASH_SCHEMA_VERSION,
    CANDIDATE_MANIFEST_SCHEMA_VERSION,
    CANDIDATE_METADATA_SCHEMA_VERSION,
    CandidateCompilationConfig,
    CandidateCompilationResult,
    CandidateValidationIssue,
    CompiledCandidateRecord,
    build_callable_module_source,
    candidate_callable_name,
    compile_candidate_callable_source,
    compile_candidate_records,
    compile_operation_to_source,
    compute_candidate_lineage_hash,
    compute_candidate_structural_hash,
    load_compiled_candidate_records,
    normalize_candidate_record,
    normalize_operation_record,
    sanitize_python_identifier,
    write_callable_module,
    write_candidate_staged_package,
)
from .connectivity import Connectivity
from .constraints import ConstraintSet
from .exporters import (
    CANONICAL_CANDIDATE_HASH_SCHEMA_VERSION,
    CANDIDATE_SCHEMA_VERSION,
    STAGED_PACKAGE_SCHEMA_VERSION,
    CandidateJsonExportConfig,
    StagedPackageJsonExportConfig,
    StagedPackageJsonExportResult,
    export_candidate_json,
    export_staged_package_json,
    write_candidate_json,
    write_staged_package_json,
)
from .lineage import LineageRecord
from .mutations import (
    detect_no_op,
    find_first_operation_on_wire,
    find_last_operation_on_wire,
    move_first_gate_to_end_on_wire,
    remove_first_gate_on_wire,
    structural_hash_operations,
    swap_first_last_gate_on_wire,
)
from .operations import (
    DEFAULT_GATE_REGISTRY,
    GateDef,
    GateRegistry,
    Operation,
    default_gate_registry,
)
from .parameters import Parameter, ParameterMap
from .templates import (
    SANZ19_TEMPLATE_IDS,
    SUPPORTED_SANZ19_LAYERS,
    build_sanz19_candidate_record,
    build_sanz19_candidate_records,
    build_sanz19_operations,
    normalize_sanz19_template_id,
)
from .validation import GeneratorValidationError, ValidationResult

CandidateCompilationBoundary = compile_candidate_records

__all__ = [
    "CANONICAL_CANDIDATE_HASH_SCHEMA_VERSION",
    "CANDIDATE_HASH_SCHEMA_VERSION",
    "CANDIDATE_MANIFEST_SCHEMA_VERSION",
    "CANDIDATE_METADATA_SCHEMA_VERSION",
    "CANDIDATE_SCHEMA_VERSION",
    "DEFAULT_GATE_REGISTRY",
    "SANZ19_TEMPLATE_IDS",
    "STAGED_PACKAGE_SCHEMA_VERSION",
    "SUPPORTED_SANZ19_LAYERS",
    "CandidateCompilationBoundary",
    "CandidateCompilationConfig",
    "CandidateCompilationResult",
    "CandidateJsonExportConfig",
    "CandidateRecord",
    "CandidateValidationIssue",
    "CompiledCandidateRecord",
    "Connectivity",
    "ConstraintSet",
    "GateDef",
    "GateRegistry",
    "GeneratorValidationError",
    "LineageRecord",
    "Operation",
    "Parameter",
    "ParameterMap",
    "StagedPackageJsonExportConfig",
    "StagedPackageJsonExportResult",
    "ValidationResult",
    "build_callable_module_source",
    "build_sanz19_candidate_record",
    "build_sanz19_candidate_records",
    "build_sanz19_operations",
    "candidate_callable_name",
    "compile_candidate_callable_source",
    "compile_candidate_records",
    "compile_operation_to_source",
    "compute_candidate_lineage_hash",
    "compute_candidate_structural_hash",
    "default_gate_registry",
    "detect_no_op",
    "export_candidate_json",
    "export_staged_package_json",
    "find_first_operation_on_wire",
    "find_last_operation_on_wire",
    "load_and_validate_campaign_spec",
    "load_campaign_spec",
    "load_compiled_candidate_records",
    "move_first_gate_to_end_on_wire",
    "normalize_candidate_record",
    "normalize_operation_record",
    "normalize_sanz19_template_id",
    "remove_first_gate_on_wire",
    "sanitize_python_identifier",
    "structural_hash_operations",
    "swap_first_last_gate_on_wire",
    "validate_campaign_spec",
    "write_callable_module",
    "write_candidate_json",
    "write_candidate_staged_package",
    "write_campaign_spec",
    "write_staged_package_json",
]
